services:
  laravel.test:
    build:
      context: .
      dockerfile: dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 8000:80
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - '.:/var/www/html'
      - ./storage/logs:/var/www/html/storage/logs
    networks:
      - sail
      - dokploy-network
    depends_on:
      - redis
      - meilisearch
      - selenium
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=Host(`visorambiental.portalinecoa.com`)"
      - "traefik.http.routers.laravel.entrypoints=websecure"
      - "traefik.http.routers.laravel.tls.certresolver=letsencrypt"
      - "traefik.http.services.laravel.loadbalancer.server.port=9000" # PHP-FPM expone el puerto 9000
      - "traefik.docker.network=dokploy-network"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000"]
      interval: 30s
      timeout: 5s
      retries: 3

  redis:
    image: 'redis:alpine'
    ports:
      - 6379:6379'
    volumes:
      - 'sail-redis:/data'
    networks:
      - sail
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

  meilisearch:
    image: 'getmeili/meilisearch:latest'
    ports:
      - 7700:7700
    volumes:
      - 'sail-meilisearch:/data.ms'
    networks:
      - sail
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
      retries: 3
      timeout: 5s

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - sail

  selenium:
    image: 'selenium/standalone-chrome'
    volumes:
      - '/dev/shm:/dev/shm'
    networks:
      - sail

  traefik:
    image: 'traefik:v2.9'
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.swarmmode=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=visorambiental@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--log.level=DEBUG" # Para más detalles en los logs
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik-certificates:/letsencrypt"
    networks:
      - sail
      - dokploy-network
    depends_on:
      - laravel.test

networks:
  sail:
    driver: bridge
  dokploy-network:
    external: true  

volumes:
  sail-mysql:
    driver: local
  sail-redis:
    driver: local
  sail-meilisearch:
    driver: local
  traefik-certificates:
    driver: local

